SELECT 
    d.NAME AS DEPARTMENT_NAME,
    COUNT(u.ID) AS EMPLOYEE_COUNT,
    AVG(u.SALARY) AS AVERAGE_SALARY
FROM 
    Users u
INNER JOIN 
    Department d ON u.DEPARTMENT_ID = d.ID
GROUP BY 
    d.NAME;
